name: CI/CD with GitOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t sheetal79/myapp:${{ github.sha }} .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.sheetal79 }}" --password-stdin

      - name: Push Docker image
        run: docker push sheetal79/myapp:${{ github.sha }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: sheetal79/myapp:${{ github.sha }}|" k8s/deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "update image to ${{ github.sha }}"
          git push
